var hierarchy =
[
    [ "nnl::action::Action", "db/d41/group__Action__Main.html#dd/d64/structnnl_1_1action_1_1Action", null ],
    [ "nnl::animation::Animation", "d6/da3/group__Animation__Main.html#d8/dc7/structnnl_1_1animation_1_1Animation", null ],
    [ "nnl::visanimation::Animation", "d7/d12/group__Subanimation__Main.html#da/d0f/structnnl_1_1visanimation_1_1Animation", null ],
    [ "nnl::animation::AnimationContainer", "d6/da3/group__Animation__Main.html#d0/d0a/structnnl_1_1animation_1_1AnimationContainer", null ],
    [ "nnl::visanimation::AnimationContainer", "d7/d12/group__Subanimation__Main.html#d3/d53/structnnl_1_1visanimation_1_1AnimationContainer", null ],
    [ "nnl::action::AnimationNode", "db/d41/group__Action__Main.html#d6/d76/unionnnl_1_1action_1_1AnimationNode", null ],
    [ "nnl::utl::Array3D< T >", "dd/d97/group__UtilityContainers.html#d9/d58/classnnl_1_1utl_1_1Array3D", null ],
    [ "nnl::utl::Array3D< nnl::collision::CollisionTest >", "dd/d97/group__UtilityContainers.html", null ],
    [ "nnl::utl::Array3D< nnl::shadow_collision::CollisionTest >", "dd/d97/group__UtilityContainers.html", null ],
    [ "nnl::model::Attachment", "da/d2b/group__Model__Main.html#da/db2/structnnl_1_1model_1_1Attachment", null ],
    [ "nnl::model::BBox", "da/d2b/group__Model__Main.html#de/d7e/structnnl_1_1model_1_1BBox", null ],
    [ "nnl::text::BitmapFont", "df/d14/group__Text__Auxiliary.html#dd/d16/structnnl_1_1text_1_1BitmapFont", null ],
    [ "nnl::text::BitmapFontParams", "df/d14/group__Text__Auxiliary.html#d5/d42/structnnl_1_1text_1_1BitmapFontParams", null ],
    [ "nnl::model::Bone", "da/d2b/group__Model__Main.html#d7/dc3/structnnl_1_1model_1_1Bone", null ],
    [ "nnl::animation::BoneAnimation", "d6/da3/group__Animation__Main.html#d8/dc0/structnnl_1_1animation_1_1BoneAnimation", null ],
    [ "nnl::colbox::ColBoxConfig", "dd/de7/group__Colbox__Main.html#de/d2c/structnnl_1_1colbox_1_1ColBoxConfig", null ],
    [ "nnl::collision::Collision", "dd/df5/group__Collision__Main.html#dd/df0/structnnl_1_1collision_1_1Collision", null ],
    [ "nnl::shadow_collision::Collision", "d7/df4/group__Shadow__Main.html#d6/d27/structnnl_1_1shadow__collision_1_1Collision", null ],
    [ "nnl::colbox::CollisionBox14", "dd/de7/group__Colbox__Main.html#df/d15/structnnl_1_1colbox_1_1CollisionBox14", null ],
    [ "nnl::colbox::CollisionBox18", "dd/de7/group__Colbox__Main.html#d0/db8/structnnl_1_1colbox_1_1CollisionBox18", null ],
    [ "nnl::colbox::CollisionBox20", "dd/de7/group__Colbox__Main.html#d0/d25/structnnl_1_1colbox_1_1CollisionBox20", null ],
    [ "nnl::collision::CollisionTest", "dd/df5/group__Collision__Main.html#d5/da8/structnnl_1_1collision_1_1CollisionTest", null ],
    [ "nnl::shadow_collision::CollisionTest", "d7/df4/group__Shadow__Main.html#d2/dff/structnnl_1_1shadow__collision_1_1CollisionTest", null ],
    [ "nnl::animation::ConvertParam", "d6/da3/group__Animation__Main.html#d6/d36/structnnl_1_1animation_1_1ConvertParam", null ],
    [ "nnl::collision::ConvertParam", "dd/df5/group__Collision__Main.html#d6/de2/structnnl_1_1collision_1_1ConvertParam", null ],
    [ "nnl::model::ConvertParam", "da/d2b/group__Model__Main.html#d8/d4a/structnnl_1_1model_1_1ConvertParam", null ],
    [ "nnl::texture::ConvertParam", "d1/da7/group__Texture__Main.html#db/d41/structnnl_1_1texture_1_1ConvertParam", null ],
    [ "nnl::collision::Edge", "dd/df5/group__Collision__Main.html#d0/d6b/structnnl_1_1collision_1_1Edge", null ],
    [ "nnl::action::EffectNode", "db/d41/group__Action__Main.html#db/d8b/unionnnl_1_1action_1_1EffectNode", null ],
    [ "nnl::Exception", "d7/d26/group__Exceptions.html#d5/d82/classnnl_1_1Exception", [
      [ "nnl::IOError", "d7/d26/group__Exceptions.html#d9/dda/classnnl_1_1IOError", null ],
      [ "nnl::NarrowError", "d7/d26/group__Exceptions.html#db/dca/classnnl_1_1NarrowError", null ],
      [ "nnl::ParseError", "d7/d26/group__Exceptions.html#de/dbb/classnnl_1_1ParseError", null ],
      [ "nnl::PreconditionError", "d7/d26/group__Exceptions.html#de/d26/classnnl_1_1PreconditionError", null ],
      [ "nnl::RangeError", "d7/d26/group__Exceptions.html#d5/df3/classnnl_1_1RangeError", null ],
      [ "nnl::RuntimeError", "d7/d26/group__Exceptions.html#d6/d99/classnnl_1_1RuntimeError", null ]
    ] ],
    [ "nnl::fog::Fog", "d7/d94/group__Fog__Main.html#db/d45/structnnl_1_1fog_1_1Fog", null ],
    [ "nnl::colbox::HitboxConfig", "dd/de7/group__Colbox__Main.html#d7/dc0/structnnl_1_1colbox_1_1HitboxConfig", null ],
    [ "nnl::action::Id", "da/da2/group__Action__Shared.html#dd/dd0/structnnl_1_1action_1_1Id", null ],
    [ "nnl::animation::KeyFrame", "d6/da3/group__Animation__Main.html#d2/d76/structnnl_1_1animation_1_1KeyFrame", null ],
    [ "nnl::visanimation::KeyFrame", "d7/d12/group__Subanimation__Main.html#d6/d91/structnnl_1_1visanimation_1_1KeyFrame", null ],
    [ "nnl::lit::Light", "d1/def/group__Light__Main.html#d5/d31/structnnl_1_1lit_1_1Light", null ],
    [ "nnl::lit::Lit", "d1/def/group__Light__Main.html#d4/de6/structnnl_1_1lit_1_1Lit", null ],
    [ "nnl::Mat4< T >", "dc/ddd/group__FixedType.html#d2/dac/structnnl_1_1Mat4", null ],
    [ "nnl::model::Material", "da/d2b/group__Model__Main.html#d5/d6a/structnnl_1_1model_1_1Material", null ],
    [ "nnl::utl::data::MD5Context", "de/d23/group__Data.html#de/dc2/classnnl_1_1utl_1_1data_1_1MD5Context", null ],
    [ "nnl::model::Mesh", "da/d2b/group__Model__Main.html#d2/d3e/structnnl_1_1model_1_1Mesh", null ],
    [ "nnl::model::MeshGroup", "da/d2b/group__Model__Main.html#d7/d99/structnnl_1_1model_1_1MeshGroup", null ],
    [ "nnl::minimap::MinimapConfig", "d3/d7c/group__Minimap__Main.html#dd/df0/structnnl_1_1minimap_1_1MinimapConfig", null ],
    [ "nnl::model::Model", "da/d2b/group__Model__Main.html#d2/dcc/structnnl_1_1model_1_1Model", null ],
    [ "nnl::Writer::Offset< T >", "da/d76/classnnl_1_1Writer_1_1Offset.html", null ],
    [ "nnl::posd::Position", "d7/d5a/group__Position__Main.html#d9/d8a/structnnl_1_1posd_1_1Position", null ],
    [ "nnl::model::Primitive", "da/d2b/group__Model__Main.html#dc/d84/structnnl_1_1model_1_1Primitive", null ],
    [ "nnl::Writer::Ref< T >", "de/de6/classnnl_1_1Writer_1_1Ref.html", null ],
    [ "nnl::render::RenderConfig", "da/dde/group__Render__Main.html#de/d55/structnnl_1_1render_1_1RenderConfig", null ],
    [ "nnl::RWBase", "dc/d8c/group__InputOutput.html#df/da8/classnnl_1_1RWBase", [
      [ "nnl::Reader", "dc/d8c/group__InputOutput.html#dc/d8a/classnnl_1_1Reader", [
        [ "nnl::BufferRW", "dc/d8c/group__InputOutput.html#d9/d59/classnnl_1_1BufferRW", null ],
        [ "nnl::BufferSpan", "dc/d8c/group__InputOutput.html#d6/d2c/classnnl_1_1BufferSpan", null ],
        [ "nnl::BufferView", "dc/d8c/group__InputOutput.html#d6/d39/classnnl_1_1BufferView", null ],
        [ "nnl::FileRW", "dc/d8c/group__InputOutput.html#d4/d65/classnnl_1_1FileRW", null ],
        [ "nnl::FileReader", "dc/d8c/group__InputOutput.html#dc/d41/classnnl_1_1FileReader", null ]
      ] ],
      [ "nnl::Writer", "dc/d8c/group__InputOutput.html#d9/d51/classnnl_1_1Writer", [
        [ "nnl::BufferRW", "dc/d8c/group__InputOutput.html#d9/d59/classnnl_1_1BufferRW", null ],
        [ "nnl::BufferSpan", "dc/d8c/group__InputOutput.html#d6/d2c/classnnl_1_1BufferSpan", null ],
        [ "nnl::FileRW", "dc/d8c/group__InputOutput.html#d4/d65/classnnl_1_1FileRW", null ]
      ] ]
    ] ],
    [ "nnl::SAnimation", "da/ddc/group__SAnimation.html#df/d3d/structnnl_1_1SAnimation", null ],
    [ "nnl::SAsset3D", "d4/d43/group__Simple3DAsset.html#d5/de4/structnnl_1_1SAsset3D", null ],
    [ "nnl::SAttachment", "d1/dc4/group__SModel.html#d7/d42/structnnl_1_1SAttachment", null ],
    [ "nnl::SAudio", "db/ddf/group__SAudio.html#d2/d0b/structnnl_1_1SAudio", null ],
    [ "nnl::SBone", "d1/dc4/group__SModel.html#d6/d25/structnnl_1_1SBone", null ],
    [ "nnl::SBoneChannel", "da/ddc/group__SAnimation.html#df/d1b/structnnl_1_1SBoneChannel", null ],
    [ "nnl::SKeyFrame< T >", "da/ddc/group__SAnimation.html#df/d10/structnnl_1_1SKeyFrame", null ],
    [ "nnl::SLight", "d4/d43/group__Simple3DAsset.html#d2/d46/structnnl_1_1SLight", null ],
    [ "nnl::SMaterial", "d1/dc4/group__SModel.html#d3/d4e/structnnl_1_1SMaterial", null ],
    [ "nnl::SMesh", "d1/dc4/group__SModel.html#d6/db7/structnnl_1_1SMesh", null ],
    [ "nnl::SModel", "d1/dc4/group__SModel.html#db/dea/structnnl_1_1SModel", null ],
    [ "nnl::SPixel", "d7/d31/group__STexture.html#d9/d88/structnnl_1_1SPixel", null ],
    [ "nnl::SPosition", "d4/d43/group__Simple3DAsset.html#d4/d94/structnnl_1_1SPosition", null ],
    [ "nnl::SSkeleton", "d1/dc4/group__SModel.html#de/d21/structnnl_1_1SSkeleton", null ],
    [ "nnl::utl::static_vector< T, Capacity >", "dd/d97/group__UtilityContainers.html#d4/df6/classnnl_1_1utl_1_1static__vector", null ],
    [ "nnl::utl::static_vector< nnl::texture::TextureData, kMaxTextureLvl >", "dd/d97/group__UtilityContainers.html", null ],
    [ "nnl::utl::static_vector< std::pair< u16, float >, 8 >", "dd/d97/group__UtilityContainers.html", null ],
    [ "nnl::utl::StaticSet< T, max_size >", "dd/d97/group__UtilityContainers.html#d6/d7d/classnnl_1_1utl_1_1StaticSet", null ],
    [ "nnl::utl::StaticSet< BoneIndex, kMaxNumBonePerPrim >", "dd/d97/group__UtilityContainers.html", null ],
    [ "nnl::STexture", "d7/d31/group__STexture.html#dd/d47/structnnl_1_1STexture", null ],
    [ "nnl::STriangle", "d1/dc4/group__SModel.html#d3/d4a/structnnl_1_1STriangle", null ],
    [ "nnl::model::SubMesh", "da/d2b/group__Model__Main.html#d8/dd3/structnnl_1_1model_1_1SubMesh", null ],
    [ "nnl::SUVAnimation", "da/ddc/group__SAnimation.html#d9/d3c/structnnl_1_1SUVAnimation", null ],
    [ "nnl::SUVChannel", "da/ddc/group__SAnimation.html#d2/d08/structnnl_1_1SUVChannel", null ],
    [ "nnl::SValue", "d0/db1/group__SimpleValue.html#dd/dfb/classnnl_1_1SValue", null ],
    [ "nnl::SVertex", "d1/dc4/group__SModel.html#dc/d68/structnnl_1_1SVertex", null ],
    [ "nnl::SVisibilityAnimation", "da/ddc/group__SAnimation.html#dd/d15/structnnl_1_1SVisibilityAnimation", null ],
    [ "nnl::text::Text", "d8/d44/group__Text__Main.html#dd/dcf/structnnl_1_1text_1_1Text", null ],
    [ "nnl::texture::Texture", "d1/da7/group__Texture__Main.html#d3/db9/structnnl_1_1texture_1_1Texture", null ],
    [ "nnl::texture::TextureData", "d1/da7/group__Texture__Main.html#d7/dbd/structnnl_1_1texture_1_1TextureData", null ],
    [ "nnl::model::TextureSwap", "da/d2b/group__Model__Main.html#d6/d9b/structnnl_1_1model_1_1TextureSwap", null ],
    [ "nnl::dig::TFileRecord< TData >", "d7/d68/group__Dig__Main.html#dd/dda/structnnl_1_1dig_1_1TFileRecord", null ],
    [ "nnl::collision::Triangle", "dd/df5/group__Collision__Main.html#da/d59/structnnl_1_1collision_1_1Triangle", null ],
    [ "nnl::shadow_collision::Triangle", "d7/df4/group__Shadow__Main.html#de/d1f/structnnl_1_1shadow__collision_1_1Triangle", null ],
    [ "nnl::model::TriangleGroup", "d3/d07/group__Model__Auxiliary.html#dd/da9/structnnl_1_1model_1_1TriangleGroup", null ],
    [ "nnl::model::UVAnimation", "da/d2b/group__Model__Main.html#d1/d52/structnnl_1_1model_1_1UVAnimation", null ],
    [ "nnl::Vec2< T >", "dc/ddd/group__FixedType.html#da/d34/structnnl_1_1Vec2", null ],
    [ "nnl::Vec3< T >", "dc/ddd/group__FixedType.html#de/de5/structnnl_1_1Vec3", null ],
    [ "nnl::Vec4< T >", "dc/ddd/group__FixedType.html#d2/d09/structnnl_1_1Vec4", null ],
    [ "nnl::vertexde::VertexLayout", "de/d26/group__Vertex__Auxiliary.html#d4/d92/structnnl_1_1vertexde_1_1VertexLayout", null ]
];